argocd:
  crds:
    install: true
  dex:
    enabled: false
  configs:
    cm:
      application.resourceTrackingMethod: label
      resource.exclusions: |
        - apiGroups:
            - ""
          kinds:
            - PersistentVolumeClaim
